version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/jot-repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
            - v3-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-dependency-cache-{{ .Branch }}
            - v3-dependency-cache
      - run:
          name: yarn
          command: yarn --frozen-lockfile install || yarn --frozen-lockfile install
      - save_cache:
          key: v3-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/backend/node_modules
            - packages/common/node_modules
            - packages/frontend/node_modules
      - run: yarn build
      # TODO: Surge env vars have been added, need to filter a deploy step to master only
      # - run: yarn deploy:frontend
      - save_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/jot-repo
