version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/CIRCLE_PROJECT_REPONAME/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: install-yarn
          command: sudo npm install --global yarn@1.9.4
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: yarn --frozen-lockfile install || yarn --frozen-lockfile install
      - save_cache:
            key: v2-dependencies-{{ checksum "yarn.lock" }}
            paths:
                - ~/repo
      - run: yarn build